development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: contributingcode_dev
  pool: 5
  username: root
  password: <%= ENV['mysql_pwd'] %>
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: contributingcode_test
  pool: 5
  username: root
  password: <%= ENV['mysql_pwd'] %>
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: contributingcode_prod
  pool: 5
  username: root
  password: <%= ENV['mysql_pwd'] %>
  socket: /tmp/mysql.sock

